# http://www.appveyor.com/docs/appveyor-yml
environment:
  matrix:
  # node.js
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

platform:
  - x86
  - x64

configuration:
  - Release

matrix:
  fast_finish: true

# Install scripts. (runs after repo cloning)
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:platform;
  - npm -g install npm
  - set PATH=%APPDATA%\npm;%PATH%
  # Typical npm stuff.
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"